version: 2
jobs:
  build:
    working_directory: /go/src/github.com/scottrigby/test-goreleaser
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: ls -lah
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  test_goreleaser_dep:
    jobs:
      - build:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.*)*/
